<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="3.0.1" />
    <PackageReference Include="Microsoft.ML.Vision" Version="3.0.1" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.3.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.18" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LeafUpload.Core\LeafUpload.Core.csproj" />
  </ItemGroup>
  <ItemGroup Label="MLModel1">
    <None Include="MLModel1.mlnet">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>